// Package inventoryv1 is the generated message contract for inventory's
// commands and events — HoldSeat, ReleaseSeatHold, SeatHeld,
// SeatHoldReleased, SeatUnavailable — and nothing else that inventory owns.
//
// # The problem
//
// A consumer in another repository — the saga, a projection, a client
// nobody at this repository has met — needs to construct a HoldSeat command
// or decode a SeatHeld event. It needs the message types and their wire
// shape. It does not need, and must not be handed, anything about how
// inventory stores a seat, which database driver it uses, or how its outbox
// works. Those are inventory's business; the message shapes are the
// contract between inventory and everyone downstream of it.
//
// # Why the obvious fixes do not work
//
// Putting the generated code inside internal/ makes it unimportable by
// anything outside this module — which is exactly what internal/ is for.
// A consumer in another repository would have no path to these types at
// all, correctly, because internal/ is doing its job.
//
// Publishing the whole service module solves the import problem but drags
// every dependency inventory has along with it, including the Postgres
// driver, the Kafka client, and everything else a message consumer has no
// use for and no business vendoring.
//
// Copying the .proto files into each consumer's own repository guarantees
// they drift: two copies of the same message, edited independently, are two
// different contracts that happen to compile.
//
// # What this package does
//
// contracts/ is its own Go module, versioned and released independently of
// the services that produce and consume these messages. A consumer adds one
// dependency and gets the message types and nothing else — no database
// driver, no service internals, no transitive weight to justify.
//
// The fully qualified name of each message — "sagaflow.inventory.v1.HoldSeat"
// and so on, set by the package line in the .proto file — is load-bearing in
// three places at once: it is the ce_type header value on every Kafka
// record, it is the value stored in the type column alongside the event's
// JSON in Postgres, and it is the protoregistry lookup key used to turn a
// stored row back into a concrete Go message when replaying history. Change
// the package line and all three shift together, silently — the generated
// code still compiles, a single process still round-trips its own messages,
// and only cross-service delivery and replay of already-stored rows break,
// somewhere else, later. fullname_test.go exists because that failure mode
// is invisible at compile time, so the names are asserted rather than
// trusted.
//
// Each .proto file here defines exactly one message. This is not a style
// preference: a second message in the same file changes what the Confluent
// wire format's message-index byte means for every message that follows it
// in that file, and breaking the rule is a silent wire failure, not a
// compile failure — the payload still encodes and decodes correctly through
// this package's own code, while every other Confluent-compatible client
// reads the wrong index and fails. See internal/platform/schema for the
// framing this rule protects.
//
// # What it deliberately does not do
//
// This package holds no logic — no validation, no defaults, no business
// rules. Everything here is generated by protoc-gen-go from the .proto
// files under proto/sagaflow/inventory/v1/, except this chapter and
// fullname_test.go. It does not
// decide how a message is framed for the wire or verified against a
// registry; that is internal/platform/schema's job, and this package is
// simply the type that schema's Serde is parameterised over.
//
// # Reading order
//
//	hold_seat.pb.go             HoldSeat, the command that starts the hold.
//	release_seat_hold.pb.go     ReleaseSeatHold, its compensating command.
//	seat_held.pb.go             SeatHeld, the event a successful hold produces.
//	seat_hold_released.pb.go    SeatHoldReleased, the compensating event.
//	seat_unavailable.pb.go      SeatUnavailable, the reply nothing else appends.
//	fullname_test.go            Why the fully qualified names are pinned.
//
// # Where this comes from
//
// Design spec §8.1 (the CloudEvents envelope, where ce_type carries the
// fully qualified name), §8.2 (.proto files as the single source of truth,
// generated into this module rather than hand-written).
package inventoryv1
