// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sagaflow/inventory/v1/seat_hold_released.proto

package inventoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SeatHoldReleased records that a live hold ended without being confirmed. It is
// how the saga learns its compensation landed, which is why inventory emits it
// even when the hold was already gone.
type SeatHoldReleased struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HoldId        string                 `protobuf:"bytes,1,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`
	BookingId     string                 `protobuf:"bytes,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	SeatId        string                 `protobuf:"bytes,3,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatHoldReleased) Reset() {
	*x = SeatHoldReleased{}
	mi := &file_sagaflow_inventory_v1_seat_hold_released_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatHoldReleased) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatHoldReleased) ProtoMessage() {}

func (x *SeatHoldReleased) ProtoReflect() protoreflect.Message {
	mi := &file_sagaflow_inventory_v1_seat_hold_released_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatHoldReleased.ProtoReflect.Descriptor instead.
func (*SeatHoldReleased) Descriptor() ([]byte, []int) {
	return file_sagaflow_inventory_v1_seat_hold_released_proto_rawDescGZIP(), []int{0}
}

func (x *SeatHoldReleased) GetHoldId() string {
	if x != nil {
		return x.HoldId
	}
	return ""
}

func (x *SeatHoldReleased) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *SeatHoldReleased) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

func (x *SeatHoldReleased) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_sagaflow_inventory_v1_seat_hold_released_proto protoreflect.FileDescriptor

const file_sagaflow_inventory_v1_seat_hold_released_proto_rawDesc = "" +
	"\n" +
	".sagaflow/inventory/v1/seat_hold_released.proto\x12\x15sagaflow.inventory.v1\"{\n" +
	"\x10SeatHoldReleased\x12\x17\n" +
	"\ahold_id\x18\x01 \x01(\tR\x06holdId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\tR\tbookingId\x12\x17\n" +
	"\aseat_id\x18\x03 \x01(\tR\x06seatId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reasonB\xef\x01\n" +
	"\x19com.sagaflow.inventory.v1B\x15SeatHoldReleasedProtoP\x01ZEgithub.com/kptac/sagaflow/contracts/sagaflow/inventory/v1;inventoryv1\xa2\x02\x03SIX\xaa\x02\x15Sagaflow.Inventory.V1\xca\x02\x15Sagaflow\\Inventory\\V1\xe2\x02!Sagaflow\\Inventory\\V1\\GPBMetadata\xea\x02\x17Sagaflow::Inventory::V1b\x06proto3"

var (
	file_sagaflow_inventory_v1_seat_hold_released_proto_rawDescOnce sync.Once
	file_sagaflow_inventory_v1_seat_hold_released_proto_rawDescData []byte
)

func file_sagaflow_inventory_v1_seat_hold_released_proto_rawDescGZIP() []byte {
	file_sagaflow_inventory_v1_seat_hold_released_proto_rawDescOnce.Do(func() {
		file_sagaflow_inventory_v1_seat_hold_released_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sagaflow_inventory_v1_seat_hold_released_proto_rawDesc), len(file_sagaflow_inventory_v1_seat_hold_released_proto_rawDesc)))
	})
	return file_sagaflow_inventory_v1_seat_hold_released_proto_rawDescData
}

var file_sagaflow_inventory_v1_seat_hold_released_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sagaflow_inventory_v1_seat_hold_released_proto_goTypes = []any{
	(*SeatHoldReleased)(nil), // 0: sagaflow.inventory.v1.SeatHoldReleased
}
var file_sagaflow_inventory_v1_seat_hold_released_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sagaflow_inventory_v1_seat_hold_released_proto_init() }
func file_sagaflow_inventory_v1_seat_hold_released_proto_init() {
	if File_sagaflow_inventory_v1_seat_hold_released_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sagaflow_inventory_v1_seat_hold_released_proto_rawDesc), len(file_sagaflow_inventory_v1_seat_hold_released_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sagaflow_inventory_v1_seat_hold_released_proto_goTypes,
		DependencyIndexes: file_sagaflow_inventory_v1_seat_hold_released_proto_depIdxs,
		MessageInfos:      file_sagaflow_inventory_v1_seat_hold_released_proto_msgTypes,
	}.Build()
	File_sagaflow_inventory_v1_seat_hold_released_proto = out.File
	file_sagaflow_inventory_v1_seat_hold_released_proto_goTypes = nil
	file_sagaflow_inventory_v1_seat_hold_released_proto_depIdxs = nil
}
